services:
  # The NodeJS App
  - type: web
    name: whatsway-platform
    env: node
    plan: free 
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL 
        sync: false
      - key: PORT
        value: 10000 
      - key: VITE_API_URL
        value: https://whatsway-platform.onrender.com 
      - key: SESSION_SECRET
        generateValue: true
